name: flutter_week4_app
description: Flutter Week 4-6 - Complete Internship Project with Provider
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Week 4 Dependencies
  http: ^1.1.0
  cupertino_icons: ^1.0.2
  
  # Week 5 Dependencies - Firebase
  firebase_core: ^3.0.0
  firebase_auth: ^5.0.0
  cloud_firestore: ^5.0.0
  
  # Week 6 Dependencies - State Management
  provider: ^6.1.1
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true