// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdZ0i0vs4twmFMxO8IRQt-Dijv9hX1dLA',
    appId: '1:998071535470:web:be6bfa5ff0b7dd9f65e37f',
    messagingSenderId: '998071535470',
    projectId: 'my-first-app-eb3f2',
    authDomain: 'my-first-app-eb3f2.firebaseapp.com',
    storageBucket: 'my-first-app-eb3f2.firebasestorage.app',
    measurementId: 'G-WVM0HLYL5H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3IDuHBi3AZYjllroz5MSplKBNi19BNHA',
    appId: '1:998071535470:android:4f9e4d2b020f1df665e37f',
    messagingSenderId: '998071535470',
    projectId: 'my-first-app-eb3f2',
    storageBucket: 'my-first-app-eb3f2.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDJcyHv2MYrz0C4-PwWsgnhO2lUbLz3TOo',
    appId: '1:998071535470:ios:3ec4217333f0c63b65e37f',
    messagingSenderId: '998071535470',
    projectId: 'my-first-app-eb3f2',
    storageBucket: 'my-first-app-eb3f2.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBdZ0i0vs4twmFMxO8IRQt-Dijv9hX1dLA',
    appId: '1:998071535470:web:8d950caa8bf8e04665e37f',
    messagingSenderId: '998071535470',
    projectId: 'my-first-app-eb3f2',
    authDomain: 'my-first-app-eb3f2.firebaseapp.com',
    storageBucket: 'my-first-app-eb3f2.firebasestorage.app',
    measurementId: 'G-SNWWPJLX83',
  );
}
